# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          # required to have terratest successfully extract output from terraform.
          # Otherwise the stdout, from where it reads output variables contians the
          # path of the terraform binary, which breaks it
          terraform_wrapper: false
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: tf
        run: |
          terraform init
          terraform apply -auto-approve
      - name: test go app
        run: |
          alias -p
          go run test.go
