# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.0.9
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.2"

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo "Hello, world!" > foo.txt
      # # Runs a single command using the runners shell
      # - name: Print foo.txt to stdout
      #   run: cat foo.txt

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo "blah" > foo2.txt
      #     cat foo2.txt
      - name: tf
        run: |
          terraform init
          terraform apply -auto-approve
      - name: test go app
        run: |
          alias -p
          go run test.go
